// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUrl = process.env["DATABASE_URL"] || "";
// Use port 5432 (session pooler / direct) for DDL / migrations / db push when connected to Supabase pooler
let directUrl = process.env["DIRECT_URL"] || dbUrl;
if (!process.env["DIRECT_URL"] && directUrl.includes(":6543")) {
  directUrl = directUrl.replace(":6543", ":5432");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directUrl || dbUrl,
  },
});
