export interface SearchModuleConfig {
  key: string;
  label: string;
  group: string;
  endpoint: string;
  route: string;
  permission?: string;
  iconName: string;
  codeField: string;
  nameField: string;
  searchFields: string[];
  subtitleBuilder: (item: any) => string;
}

export const SEARCH_MODULES: SearchModuleConfig[] = [
  {
    key: 'raw-materials',
    label: 'Raw Materials',
    group: 'Inventory',
    endpoint: '/api/raw-materials',
    route: 'inventory_raw',
    permission: 'inventory_raw:view',
    iconName: 'Package',
    codeField: 'code',
    nameField: 'name',
    searchFields: ['code', 'name', 'grade', 'category', 'subCategory', 'description', 'hsnCode', 'supplier', 'warehouse'],
    subtitleBuilder: (item) => `Stock: ${item.currentStock ?? 0} ${item.uom || 'Kg'} • Grade: ${item.grade || 'N/A'} • ${item.supplier?.supplierName || item.supplierName || 'Direct'}`,
  },
  {
    key: 'products',
    label: 'Finished Products',
    group: 'Inventory',
    endpoint: '/api/products',
    route: 'inventory_products',
    permission: 'inventory_products:view',
    iconName: 'Boxes',
    codeField: 'code',
    nameField: 'name',
    searchFields: ['code', 'name', 'boxType', 'category', 'subCategory', 'dimensions', 'hsnCode', 'warehouse'],
    subtitleBuilder: (item) => `Type: ${item.boxType || 'Standard Box'} • Available: ${item.availableStock ?? 0} ${item.unit || 'Pcs'} • Price: ₹${item.sellingPrice || item.costPrice || 0}`,
  },
  {
    key: 'sales-orders',
    label: 'Sales Orders',
    group: 'Sales & CRM',
    endpoint: '/api/sales/orders',
    route: 'sales_orders',
    permission: 'sales:view',
    iconName: 'FileText',
    codeField: 'soNumber',
    nameField: 'customerName',
    searchFields: ['soNumber', 'customerName', 'customerPoNumber', 'productName', 'salesExecutive', 'status'],
    subtitleBuilder: (item) => `PO: ${item.customerPoNumber || 'N/A'} • Product: ${item.productName || item.product?.name || 'N/A'} • Qty: ${item.quantity ?? 0} • Status: ${item.status || 'Draft'}`,
  },
  {
    key: 'work-orders',
    label: 'Work Orders',
    group: 'Production',
    endpoint: '/api/production/work-orders',
    route: 'production_work_orders',
    permission: 'production:view',
    iconName: 'ClipboardList',
    codeField: 'orderNumber',
    nameField: 'productName',
    searchFields: ['orderNumber', 'productName', 'salesOrder', 'status', 'supervisor', 'assignedLine', 'currentStage'],
    subtitleBuilder: (item) => `Stage: ${item.currentStage || 'Planning'} • Qty: ${item.orderedQuantity ?? 0} • Status: ${item.status || 'Draft'}${item.salesOrder?.soNumber ? ` • SO: ${item.salesOrder.soNumber}` : ''}`,
  },
  {
    key: 'purchase-orders',
    label: 'Purchase Orders',
    group: 'Procurement',
    endpoint: '/api/purchase-orders',
    route: 'procurement_po',
    permission: 'procurement:view',
    iconName: 'ShoppingCart',
    codeField: 'poNumber',
    nameField: 'supplierName',
    searchFields: ['poNumber', 'rfqNumber', 'supplier', 'status'],
    subtitleBuilder: (item) => `Supplier: ${item.supplier?.supplierName || item.supplierName || 'N/A'} • Status: ${item.status || 'Draft'} • Total: ₹${item.totalAmount ?? 0}`,
  },
  {
    key: 'customers',
    label: 'Customers',
    group: 'Sales & CRM',
    endpoint: '/api/sales/customers',
    route: 'sales_customers',
    permission: 'sales:view',
    iconName: 'Users',
    codeField: 'code',
    nameField: 'name',
    searchFields: ['code', 'name', 'contactPerson', 'phone', 'email', 'salesExecutive'],
    subtitleBuilder: (item) => `Contact: ${item.contactPerson || 'N/A'} • ${item.phone || item.email || item.salesExecutive || 'Active Customer'}`,
  },
  {
    key: 'suppliers',
    label: 'Suppliers & Mills',
    group: 'Procurement',
    endpoint: '/api/suppliers',
    route: 'inventory_suppliers',
    permission: 'suppliers:view',
    iconName: 'Truck',
    codeField: 'supplierCode',
    nameField: 'supplierName',
    searchFields: ['supplierCode', 'supplierName', 'millName', 'category'],
    subtitleBuilder: (item) => `Mill: ${item.millName || 'N/A'} • Category: ${item.category || 'General'}`,
  },
  {
    key: 'sales-quotations',
    label: 'Quotations',
    group: 'Sales & CRM',
    endpoint: '/api/sales/quotations',
    route: 'sales_quotations',
    permission: 'sales:view',
    iconName: 'FileText',
    codeField: 'quotationNumber',
    nameField: 'customerName',
    searchFields: ['quotationNumber', 'customerName', 'productName', 'salesExecutive', 'status'],
    subtitleBuilder: (item) => `Product: ${item.productName || 'N/A'} • Amount: ₹${item.amount ?? 0} • Status: ${item.status || 'Pending'}`,
  },
  {
    key: 'sales-leads',
    label: 'Sales Leads',
    group: 'Sales & CRM',
    endpoint: '/api/sales/leads',
    route: 'sales_leads',
    permission: 'sales:view',
    iconName: 'Users',
    codeField: 'leadNumber',
    nameField: 'customerName',
    searchFields: ['leadNumber', 'customerName', 'contactPerson', 'phone', 'email', 'productRequirement'],
    subtitleBuilder: (item) => `Req: ${item.productRequirement || 'N/A'} • Status: ${item.status || 'Lead'} • Exec: ${item.assignedSalesExecutive || 'Unassigned'}`,
  },
  {
    key: 'cost-sheets',
    label: 'Cost Sheets',
    group: 'Costing',
    endpoint: '/api/costing',
    route: 'costing_sheets',
    permission: 'costing:view',
    iconName: 'Calculator',
    codeField: 'costSheetNumber',
    nameField: 'productName',
    searchFields: ['costSheetNumber', 'title', 'productName', 'customerName', 'boxType'],
    subtitleBuilder: (item) => `Customer: ${item.customerName || 'N/A'} • Box: ${item.boxType || 'Universal'} • Qty: ${item.targetQuantity ?? 0}`,
  },
  {
    key: 'boms',
    label: 'Bills of Material',
    group: 'Production',
    endpoint: '/api/production/boms',
    route: 'costing_bom',
    permission: 'costing:view',
    iconName: 'Layers',
    codeField: 'bomNumber',
    nameField: 'name',
    searchFields: ['bomNumber', 'name', 'productName', 'customerName', 'fluteType'],
    subtitleBuilder: (item) => `Product: ${item.product?.name || item.productCode || 'N/A'} • Flute: ${item.fluteType || 'N/A'} • Ply: ${item.ply ?? 5}`,
  },
  {
    key: 'dispatches',
    label: 'Dispatches & Challans',
    group: 'Logistics & QC',
    endpoint: '/api/sales/dispatch',
    route: 'dispatch_view',
    permission: 'dispatch:view',
    iconName: 'Truck',
    codeField: 'challanNumber',
    nameField: 'customerName',
    searchFields: ['challanNumber', 'soNumber', 'customerName', 'vehicleNumber', 'driverName', 'transporterName'],
    subtitleBuilder: (item) => `SO: ${item.soNumber || 'N/A'} • Vehicle: ${item.vehicleNumber || 'N/A'} • Status: ${item.status || 'Dispatched'}`,
  },
  {
    key: 'rfqs',
    label: 'Procurement RFQs',
    group: 'Procurement',
    endpoint: '/api/rfqs',
    route: 'procurement_rfq',
    permission: 'procurement:view',
    iconName: 'FileText',
    codeField: 'rfqNumber',
    nameField: 'description',
    searchFields: ['rfqNumber', 'department', 'description', 'status'],
    subtitleBuilder: (item) => `Dept: ${item.department || 'Procurement'} • Priority: ${item.priority || 'Medium'} • Status: ${item.status || 'Draft'}`,
  },
  {
    key: 'gate-entries',
    label: 'Gate Entries',
    group: 'Procurement',
    endpoint: '/api/gate-entries',
    route: 'procurement_gate_entry',
    permission: 'procurement:view',
    iconName: 'Truck',
    codeField: 'gateEntryNumber',
    nameField: 'vehicleNumber',
    searchFields: ['gateEntryNumber', 'poNumber', 'vehicleNumber', 'driverName', 'challanNumber'],
    subtitleBuilder: (item) => `Vehicle: ${item.vehicleNumber || 'N/A'} • PO: ${item.poNumber || item.purchaseOrder?.poNumber || 'N/A'} • Driver: ${item.driverName || 'N/A'}`,
  },
  {
    key: 'reel-inwards',
    label: 'Reel Inwards',
    group: 'Procurement',
    endpoint: '/api/reel-inwards',
    route: 'procurement_reel_inward',
    permission: 'procurement:view',
    iconName: 'Package',
    codeField: 'inwardNumber',
    nameField: 'supplierName',
    searchFields: ['inwardNumber', 'reelNumber', 'challanNumber', 'invoiceNumber', 'poNumber', 'supplierName', 'millName'],
    subtitleBuilder: (item) => `Mill: ${item.millName || item.supplierName || 'N/A'} • Reel: ${item.reelNumber || 'N/A'} • Status: ${item.status || 'Pending'}`,
  },
  {
    key: 'quality-checks',
    label: 'Quality Checks',
    group: 'Logistics & QC',
    endpoint: '/api/quality-checks',
    route: 'procurement_qc',
    permission: 'procurement:view',
    iconName: 'ShieldAlert',
    codeField: 'qcNumber',
    nameField: 'qcType',
    searchFields: ['qcNumber', 'referenceNumber', 'inspector', 'stage', 'result', 'status'],
    subtitleBuilder: (item) => `Type: ${item.qcType || 'QC'} • Result: ${item.result || item.status || 'Pending'} • Inspector: ${item.inspector || 'N/A'}`,
  },
  {
    key: 'warehouses',
    label: 'Warehouses',
    group: 'Inventory',
    endpoint: '/api/warehouses',
    route: 'inventory_warehouses',
    permission: 'warehouses:view',
    iconName: 'Warehouse',
    codeField: 'code',
    nameField: 'name',
    searchFields: ['code', 'name', 'location', 'manager'],
    subtitleBuilder: (item) => `Location: ${item.location || 'HQ'} • Manager: ${item.manager || 'Unassigned'} • Status: ${item.status || 'Operational'}`,
  },
  {
    key: 'categories',
    label: 'Categories',
    group: 'Inventory',
    endpoint: '/api/categories',
    route: 'inventory_categories',
    permission: 'categories:view',
    iconName: 'Layers',
    codeField: 'code',
    nameField: 'name',
    searchFields: ['code', 'name', 'description'],
    subtitleBuilder: (item) => `Type: ${item.type || 'General'} • Status: ${item.status || 'Active'}`,
  },
  {
    key: 'users',
    label: 'Staff & Users',
    group: 'Administration',
    endpoint: '/api/users',
    route: 'user_management',
    permission: 'users:view',
    iconName: 'Users',
    codeField: 'email',
    nameField: 'name',
    searchFields: ['name', 'email', 'department'],
    subtitleBuilder: (item) => `Dept: ${item.department || 'General'} • Role: ${item.role?.name || item.role || 'Staff'}`,
  },
];
